# Generated by Django 4.1.6 on 2023-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_comment_bid_auction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to='auctions/photos'),
        ),
    ]
