# Generated by Django 4.1.6 on 2023-02-06 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchers',
            field=models.ManyToManyField(null=True, related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
