# Generated by Django 4.1.6 on 2023-02-06 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_category_alter_auction_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
