# Generated by Django 4.1.6 on 2023-02-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ('start_time',)},
        ),
    ]
