# Generated by Django 4.1.6 on 2023-03-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
